spring.application.name=api-sistemaVendas

spring.datasource.url=jdbc:postgresql://${API_DB_HOST}:${API_DB_PORT}/${API_DB_NAME}
spring.datasource.username=${API_DB_USER}
spring.datasource.password=${API_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-slq=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080